export default {
  colors: {
    primary: '#f06514',
    primary20: '#fad0b7',
    black: '#04151f',
    grey: '#8c8c8c',
    lightGrey: '#bfbfbf',
    darkGrey: '#262626',
    tertiary: '#262626',
    white: '#ffffff',
    inputFill: '#ffffff',
    inputOutline: '#ffffff',
    shadowColor: '#04151f',
    success: '#27a300',
    error: '#ff0000',
  },
  sizes: {
    borderRadius: 8,
  },
  spacing: {
    xxs: 2,
    xs: 4,
    s: 8,
    sm: 12,
    m: 16,
    l: 24,
    xl: 32,
    xxl: 64,
  },
  fonts: {
    PRIMARY_FONT_REGULAR: undefined,
    PRIMARY_FONT_SEMI: undefined,
    PRIMARY_FONT_BOLD: undefined,
  },
};
